const data = {
    "ethio ludo": "ኢትዮ ሉዶ",
    "ludo": "ሉዶ",
    "master": "ማስተር",
    "roll the dice, rule the game!": "ዳይሱን ያዙሩ፣ ጨዋታውን ይቆጣጠሩ",
    "leaderboard": "የመሪዎች ሰሌዳ",
    "account": "መለያ",
    "pass & play": "ይለፉ እና ይጫወቱ",
    "play locally with friends": "በአቅራቢያዎ ካሉ ጓደኞችዎ ጋር ይጫወቱ",
    "computer": "ኮምፒዩተር",
    "vs computer": "ከኮምፒዩተር ጋር",
    "play against ai bots": "ከኤአይ ቦቶች ጋር ይጫወቱ",
    "play worldwide": "በአለምአቀፍ ደረጃ ይጫወቱ",
    "online play": "ኦንላይን ጨዋታ",
    "play online with friends.": "ኦንላይን ከጓደኞችዎ ጋር ይጫወቱ",
    "select players": "ተጫዋቾች ይምረጡ",
    "how many players will be playing?": "ስንት ተጫዋቾች ይኖራሉ?",
    "2 players": "2 ተጫዋቾች",
    "3 players": "3 ተጫዋቾች",
    "4 players": "4 ተጫዋቾች",
    "continue": "ቀጥል",
    "each player will take turns on the same device": "ሁሉም ተጫዋቾች በየተራ በተመሳሳይ መሳሪያ ይጫወታሉ",
    "enter player names to start": "የተጫዋቾቹን ስም ያስገቡ",
    "4 players game": "4 ተጫዋቾች ጨዋታ",
    "red": "ቀይ",
    "green": "አረንጓዴ",
    "yellow": "ቢጫ",
    "blue": "ሰማያዊ",
    "start game": "ጨዋታ ጀምር",
    "player 1": "ተጫዋች 1",
    "player 2": "ተጫዋች 2",
    "player 3": "ተጫዋች 3",
    "player 4": "ተጫዋች 4",
    "loading game": "ጨዋታው እየጫነ ነው",
    "you will play against ai controlled bots": "ከኤአይ ቦቶች ተቃራኒ ይጫወታሉ",
    "sign in": "ይግቡ",
    "master your moves, anytime, anywhere!": "እንቅስቃሴዎን ያዳብሩ በማንኛውም ጊዜ፣ በማንኛውም ቦታ",
    "sign in with your phone number": "በስልክ ቁጥርዎ ይግቡ",
    "quick access": "ፈጣን መድረሻ",
    "new to ludo - create account": "ለሉዶ አዲስ ነዎት - መለያ ይክፈቱ",
    "select game size": "የጨዋታ መጠን ምረጡ",
    "how many players do you want to play with?": "ከስንት ተጫዋቾች ጋር መጫወት ይፈልጋሉ",
    "back": "ተመለስ",
    "back to menu": "ወደ ማውጫ ተመለስ",
    "looking for players...": "ተጫዋቾች በመፈለግ ላይ",
    "time left": "ቀሪ ጊዜ",
    "game mode": "የጨዋታ ሁኔታ",
    "status": "ሁኔታ",
    "searching worldwide": "በአለምአቀፍ ደረጃ እየፈለገ",
    "matched": "ተዛምዷል",
    "total active": "ጠቅላላ ንቁ",
    "1 worldwide": "1 አለምአቀፍ",
    "game tip:": "የጨዋታ ጠቃሚ ምክሮች",
    "focus on blocking your opponent's main path!": "የተቀናቃኝዎትን መንገድ መዝጋት ላይ ያትኩሩ",
    "cancel search": "ፍለጋ አቋርጥ",
    "account details": "የመለያ ዝርዝር መረጃ",
    "today's score": "የዛሬ ውጤት",
    "games played today": "ዛሬ የተጫወትናቸው ጨዋታዎች",
    "sign out": "ዘግተህ ውጣ",
    "loading...": "እየከፈተ ነው...",
    "entry fee": "የመግቢያ ክፍያ", 
    "coins": "ሳንቲሞች",  
    "get started": "ጀምር",
    "enter your number to start playing ethio ludo!": "የኢትዮ ሉዶ ጨዋታ ለማስጀመር ቁጥሮን ያስገቡ!",
    "phone number": "ስልክ ቁጥር",
    "ludo nickname (optional)": "የሉዶ ቅጽል ስም (ከተፈለገ)",
    "enjoy the game": "በጨዋታው ይደሰቱ",
    "by continuing, you agree to our terms of service.": "በመቀጠልዎ በአገልግሎት ውላችን ተስማምተዋል።",
    "something went wrong. please try again.": "የሆነ ችግር ተከስቷል። እባክዎ እንደገና ይሞክሩ።",
    "players": "ተጫዋቾች", 
    "total players": "አጠቃላይ ተጫዋቾች",
    "you": "አንተ/አንቺ",
    "bot 1": "ቦት 1",
    "bot 2": "ቦት 2",
    "bot 3": "ቦት 3",
    "enter name...": "ስሞትን ያስገቡ...",
    "creating game...": "ጨዋታ በመፍጠር ላይ...",
    "insufficient coins! you need at least 100 coins to play vs computer.": "እባኮ በቂ ሂሳብ የሎትም፣ ጨዋታውን ለመጀመር ቢያንስ 100 ሳንቲም ያስፈልጎታል",
    "e.g. 0912345678": "ምሳሌ፡ 0912345678",
    "e.g. diceking99": "ምሳሌ፡ DiceKing99",
    "leave lobby": "መቀበያ ክፍሉን ለቀህ ውጣ",
    "waiting for host to start the game": "አዘጋጁ ጨዋታውን እስኪጀምር በመጠባበቅ ላይ",
    "rank": "ደረጃ",
    "name": "ስም",
    "uid": "ዩአይዲ",
    "wins": "ድሎች",
    "matches": "የተጫወቷቸው ጨዋታዎች",
    "winrate": "የማሸነፍ መጠን",
    "you ran out of time, one life lost": "ጊዜህ አልቋል፣ አንድ እድል ቀንሷል",
    "share the game id above with your friends. they can join by clicking \"join game\" from the main menu and entering this id.": "ከላይ ያለውን የጨዋታ መለያ ቁጥር (አይዲ) ለጓደኞችህ አጋራ። በዋናው ማውጫ ላይ 'ጨዋታውን ተቀላቀል' የሚለውን በመጫንና ይህን መለያ ቁጥር በማስገባት ጨዋታውን መቀላቀል ይችላሉ",
    "how to invite friends:": "ጓደኞችን እንዴት መጋበዝ ይቻላል?",
    "waiting for player": "ተጫዋች በመጠባበቅ ላይ",
    "ready": "ዝግጁ",
    "host": "አዘጋጅ",
    "share this id with your friends to join": "እንዲቀላቀሉ ይህንን መለያ ቁጥር ለጓደኞችህ አጋራ",
    "copy": "ኮፒ",
    "all players have joined": "ሁሉም ተጫዋቾች ገብተዋል",
    "game lobby": "የጨዋታ መቀበያ ክፍል (ሎቢ)",
    "ready to start": "ለመጀመር ዝግጁ ነው",
    "return to menu": "ወደ ዝርዝር ማውጫ ተመለስ",
    "please try again later.": "እባክህ ቆይተህ እንደገና ሞክር",
    "we couldn't find anyone worldwide to play with you right now.": "በአሁኑ ሰዓት ከእርስዎ ጋር የሚጫወት ሰው በዓለም ዙሪያ ማግኘት አልቻልንም።",
    "no player found": "ምንም ተጫዋች አልተገኘም",
    "preparing game": "ጨዋታው በመዘጋጀት ላይ ነው",
    "time": "ጊዜ",
    "active": "በጨዋታ ላይ ያለ",
    "lobby": "መቀበያ ክፍል (ሎቢ)",
    "search timeout": "የመፈለጊያ ጊዜ አልፏል",
    "player connected": "ተጫዋች ተገናኝቷል",
    "looking for master players...": "ማስተር ተጫዋቾችን በመፈለግ ላይ...",
    "searching": "በመፈለግ ላይ",
    "entry amount": "መግቢያ ዋጋ",
    "classic": "ክላሲክ",
    "online multiplayer": "በኢንተርኔት ብዙ ሆነው ይጫወቱ",
    "entry": "መግቢያ",
    "tournament play": "የውድድር ጨዋታ",
    "home": "መነሻ ገጽ",
    "try again": "እንደገና ሞክር",
    "quit": "ውጣ",
    "winner": "አሸናፊ",
    "you won!": "አሸንፈሃል/ሻል!",
    "game over": "ጨዋታው ተጠናቋል",
    "ultimate ludo superstar champion!": "የሉዶ ልዕለ-ኮከብ ሻምፒዮን!",
    "better luck next time, superstar": "በሚቀጥለው ጊዜ ይሳካልሃል፣ ሱፐር-ስታር!",
    "total wins": "ጠቅላላ ድሎች",
    "ludo champ": "የሉዶ ሻምፒዮን",
    "loading master profile": "የማስተር ፕሮፋይል በመክፈት ላይ",
    "ask your host for the room id to join the match correctly": "በጨዋታው በትክክል ለመሳተፍ አዘጋጁን የክፍል መለያ ቁጥሩን ጠይቅ",
    "joining": "በመቀላቀል ላይ",
    "join & pay": "ተቀላቀል እና ክፈል",
    "enter game id": "የጨዋታ መለያ ቁጥሩን አስገባ",
    "exit to menu": "ወደ ዝርዝር ማውጫ ተመለስ",  
    "go to lobby": " ወደ መቀበያ ክፍል ሂድ",  
    "copy id": "መለያ ቁጥሩን ቅዳ",
    "room id": " የክፍል መለያ",    
    "share the room id with your friends": "ለመቀላቀል ይህንን መለያ ቁጥር ለጓደኞችህ አጋራ",  
    "game ready": "ጨዋታው ዝግጁ ነው",
    "create & pay": "ፍጠር እና ክፈል",
    "choose how you want to play": "እንዴት መጫወት እንደሚፈልጉ ይምረጡ",
    "enter a room id to join your friends": "ጓደኞችህን ለመቀላቀል የጨዋታ ክፍል(ሎቢ) መለያ ቁጥር አስገባ",
    "join game": "ጨዋታውን ተቀላቀል", 
    "start a new room and invite your friends": "አዲስ የጨዋታ ክፍል በመክፈት ጓደኞችህን ጋብዝ",
    "event": "ክስተቶች",
    "adda": "መወያያ",
    "inventory": "ዕቃዎች",
    "social": "ማህበራዊ",
    "online": "ኦንላይን",
    "team up": "ቡድን",
    "friends": "ጓደኞች",
    "redeem vault": "ካዝናውን ይቀይሩ", 
    "exchange your hard-earned ludo coins for real money": " የደከሙበትን የሉዶ ሳንቲሞች ወደ እውነተኛ ገንዘብ ይቀይሩ", 
    "coins available": "ያሉዎት ሳንቲሞች",
    "redeem now": " አሁኑኑ ይቀይሩ",  
    "redeem coins": " ሳንቲሞችን ይቀይሩ",  
    "request submitted!": "ጥያቄው ገብቷል!",
    "your request to redeem": "የመቀየር ጥያቄዎት",
    "for": "ለ",
    "coins has been submitted and is pending review.": "ሳንቲሞች ገብቷል እና በመገምገም ላይ ነው።",
    "close": "ዝጋ",
    "redemption history": "የተቀያሪ ታሪክ",
    "coins spent": "የወጣ ሳንቲም",
    "usd amount": "የዶላር መጠን",
    "date & time": "ቀን እና ሰዓት",
    "pending": "በመጠባበቅ ላይ",
    "approved": "ጸድቋል",
    "rejected": "ውድቅ ተደርጓል",
    "no redemption history found.": " ምንም የተቀያሪ ታሪክ አልተገኘም።",
    "create game": "ጨዋታ ፍጠር", 
    "playing online requires a stable internet connection": "ኦንላይን ለመጫወት አስተማማኝ የኢንተርኔት ግንኙነት ያስፈልጋል",
    "create room": "ክፍል ፍጠር",   
    "join room": "ክፍል ተቀላቀል",  
    "match entry fee": "የመግቢያ ክፍያ",  
    "your display name": "የእርስዎ ስም",    
    "max players": " ከፍተኛ ተጫዋቾች",
    "create & pay 100 🪙": "ፍጠር እና 100 🪙 ክፈል",  
    "process...": "በሂደት ላይ...",
    "game ready!": "ጨዋታው ዝግጁ ነው!", 
    "enter 6-digit id": "የ 6-አሃዝ መለያ ያስገቡ",
    "join & pay 100 🪙": "ተቀላቀል እና 100 🪙 ክፈል",
    "joining...": "በመቀላቀል ላይ...",
    "ask your host for the room id to join the match correctly.": "ትክክለኛውን ጨዋታ ለመቀላቀል አዘጋጁን የክፍል መለያ ይጠይቁ።", 
    "win rate": "የማሸነፍ መጠን",
    "loss": "ሽንፈት",
    "better luck next time, superstar!": "ለሚቀጥለው ጊዜ የተሻለ ዕድል፣ ሱፐርስታር!",
    "searching...": "በመፈለግ ላይ...",
    "player connected!": "ተጫዋች ተገናኝቷል!",
    "preparing game...": "ጨዋታ በመፍጠር ላይ...",
    "no player found!": "ምንም ተጫዋች አልተገኘም!",
    "all players have joined!": "ሁሉም ተጫዋቾች ተቀላቅለዋል!",
    "waiting for": "በመጠበቅ ላይ",
    "more player(s)": "ተጨማሪ ተጫዋች(ች)",
    "need": "ያስፈልጋል",
    "game id": "የጨዋታ መለያ",
    "waiting for host to start the game...": "አስተናጋጁ ጨዋታውን እስኪጀምር በመጠበቅ ላይ...",
    "daily mission": "የእለቱ ተልዕኮ",
    "weekly rewards": "የሳምንቱ ሽልማቶች",
    "resets in": "ዳግም ይጀመራል በ",
    "day": "ቀን",
    "claim": "ውሰድ",
    "locked": "ተዘግቷል",
    "claim all rewards": "ሁሉንም ሽልማቶች ውሰድ",
    "open ludo chat": "የሉዶ ጭዋታ ክፈት",
    "win 500 coins": "500 ሳንቲሞች አሸንፍ",
    "play 1 match": "1 ጨዋታ ተጫወት",
    "roll 6 two times": "6 ቁጥርን ሁለት ጊዜ አውጣ",
    "send 1 gift": "1 ስጦታ ላክ",
    "guest player": "እንግዳ ተጫዋች",
    "not logged in": "አልገቡም",
    "weekly gift": "የሳምንቱ ስጦታ",
    "ready to collect!": "ለመውሰድ ዝግጁ ነው!",
    "winner announcement": "የአሸናፊዎች ማስታወቂያ",
    "just won": "አሁን አሸንፏል",
    "view all": "ሁሉንም ይመልከቱ",
    "play online": "ኦንላይን ይጫወቱ",
    "play with real players": "ከእውነተኛ ተጫዋቾች ጋር ይጫወቱ",
    "pass n play": "ይለፉ እና ይጫወቱ",
    "play with friends on the same device": "በተመሳሳይ መሳሪያ ላይ ከጓደኞችዎ ጋር ይጫወቱ",
    "play with computer": "ከኮምፒዩተር ጋር ይጫወቱ",
    "play against ai opponent": "ከኤአይ ተቃዋሚ ጋር ይጫወቱ",
    "collect your reward!": "ሽልማትዎን ይውሰዱ!",
    "view top players": "ከፍተኛ ተጫዋቾችን ይመልከቱ",
    "view your profile": "ፕሮፋይሎን ይመልከቱ",
    "background music": "የጀርባ ሙዚቃ",
    "safe & fair": "ደህንነቱ የተጠበቀ እና ፍትሃዊ",
    "100% secure gameplay": "100% ደህንነቱ የተጠበቀ ጨዋታ",
    "private table": "የግል ጠረጴዛ",
    "create & play with friends": "ይፍጠሩ እና ከጓደኞችዎ ጋር ይጫወቱ",
    "read our terms of service": "የአገልግሎት ውላችንን ያንብቡ",
    "daily reward": "የእለቱ ሽልማት",
    "login daily & win rewards": "በየቀኑ ይግቡ እና ሽልማቶችን ያሸንፉ",
    "buy coins": "ሳንቲሞችን ይግዙ",
    "coin shop": "የሳንቲም ሱቅ",
    "select package": "ፓኬጅ ይምረጡ",
    "get coins to play more and win big!": "ተጨማሪ ለመጫወት እና ለማሸነፍ ሳንቲሞችን ያግኙ!",
    "buy": "ግዛ",
    "best value": "ምርጥ ዋጋ",
    "secure payment methods": "አስተማማኝ የክፍያ አማራጮች",
    "credit balance": "የሂሳብ መጠን",
    "statistics": "ስታቲስቲክስ",
    "add your status...": "ሁኔታዎን ያክሉ...",
    "level": "ደረጃ",
    "games won": "ያሸነፉት ጨዋታ", 
    "games lost": "የተሸነፉት ጨዋታ", 
    "win streak": "ተከታታይ ድሎች",
    "tokens captured": "የተያዙ ቶከኖች",
    "tokens killed": "የተገደሉ ቶከኖች",
    "performance rating": "የአፈጻጸም ደረጃ",
    "tournaments won": "ያሸነፉት ውድድሮች",
    "save data": "መረጃ አስቀምጥ",
    "change device": "መሳሪያ ቀይር",
    "win more": "ተጨማሪ አሸንፍ",
    "edit profile": "ፕሮፋይል ቀይር",
    "tournaments": "ውድድሮች",
    "daily tasks": "የእለቱ ተግባራት",
    "no game data found": "የጨዋታ መረጃ አልተገኘም",
    "return home": "ወደ መነሻ ገጽ ተመለስ",
    "playing online requires a stable internet connection": "ኦንላይን ለመጫወት አስተማማኝ የኢንተርኔት ግንኙነት ያስፈልጋል",
    "loading champions...": "አሸናፊዎችን በመጫን ላይ...",
    "select players": "ተጫዋቾችን ይምረጡ",
    "share the room id with your friends": "የክፍል መለያ ቁጥሩን ለጓደኞችዎ ያጋሩ",
    "game center": "የጨዋታ ማእከል",
    "legal terms & gameplay rules": "ህጋዊ ውሎች እና የጨዋታ ህጎች",
    "terms & conditions": "ውሎች እና ግዴታዎች",
    "how to play": "እንዴት መጫወት ይቻላል",
    "fair play": "ታማኝ ጨዋታ",
    "any form of cheating or exploitation will lead to an immediate ban.": "ማንኛውም የማጭበርበር ሙከራ ወዲያውኑ ከጨዋታው ያስታግዳል።",
    "account security": "የመለያ ደህንነት",
    "users are responsible for their account credentials.": "ተጠቃሚዎች ለመለያ መረጃዎቻቸው ተጠያቂ ናቸው።",
    "virtual currency": "ዲጂታል ሳንቲሞች",
    "coins are for in-game use and have no real-world cash value outside the redemption platform.": "ሳንቲሞች በጨዋታው ውስጥ ብቻ ጥቅም ላይ የሚውሉ ሲሆን ከመቤዠት መድረክ ውጭ ምንም አይነት የገንዘብ ዋጋ የላቸውም።",
    "community conduct": "የማህበረሰብ ስነ-ምግባር",
    "be respectful to other players in online matches.": "በኦንላይን ጨዋታዎች ላይ ለሌሎች ተጫዋቾክ አክብሮት ይኑርዎት።",
    "objective": "አላማ",
    "move all four of your tokens to the finish (home) area before your opponents.": "ተቃዋሚዎችዎ ሳይቀድሙዎት አራቱንም ቶከኖችዎ ወደ መጨረሻው (ቤት) ያድርሱ።",
    "movement": "እንቅስቃሴ",
    "roll the dice to move tokens. a 6 is required to bring a token out of the starting area.": "ቶከኖችን ለማንቀሳቀስ ዳይሱን ያንከባለሉ። ቶከን ከቤት ለማውጣት 6 ቁጥር ያስፈልጋል።",
    "capturing": "መያዝ/መግደል",
    "landing on an opponent's token sends it back to their start.": "በተቃዋሚ ቶከን ላይ ማረፍ ወደ መጀመሪያው ቦታ ይመልሰዋል።",
    "safe squares": "ደህንነታቸው የተጠበቁ ቦታዎች",
    "tokens on squares with icons are safe from being captured.": "ምልክት ያለባቸው ቦታዎች ላይ ያሉ ቶከኖች አይገደሉም ወይም አይያዙም።",
    "disclaimer": "ማሳሰቢያ",
    "ethio ludo is intended for entertainment purposes only. please play responsibly.": "ኢትዮ ሉዶ ለመዝናኛ ዓላማ ብቻ የተዘጋጀ ነው። እባክዎ በኃላፊነት ይጫወቱ።",
    "wheel of coins": "የሳንቲሞች ጎማ",
    "tap": "ይንኩ",
    "spin": "ያሽከርክሩ",
    "done": "ተጠናቋል",
    "you've already spun today! come back tomorrow.": "ዛሬ አሽከርክረዋል! ነገ ተመልሰው ይምጡ።",
    "premium spin": "ልዩ ሽክርክሪት",
    "lucky!": "እድለኛ!",
    "oops!": "ውይ!",
    "free spin": "ነጻ ሽክርክሪት",
    "better luck next time": "ለሚቀጥለው ጊዜ የተሻለ እድል",
    "back to home": "ወደ መነሻ ተመለስ",
    "collect coins": "ሳንቲሞችን ሰብስብ",
    "spin now": "አሁኑኑ አሽከርክር",
    "play again": "እንደገና ተጫወት",
    "master profile": "ማስተር ፕሮፋይል",
    "loading master profile...": "ማስተር ፕሮፋይል በመጫን ላይ...",
    "insufficient coins! keep playing to earn more.": "በቂ ሳንቲም የለም! ተጨማሪ ለማግኘት መጫወትዎን ይቀጥሉ።",
    "successfully redeemed": "በተሳካ ሁኔታ ተበዝቷል",
    "details have been sent to your email.": "ዝርዝሮች ወደ ኢሜልዎ ተልከዋል።",
    "redemption failed. please try again.": "መበዝያው አልተሳካም። እባክዎ እንደገና ይሞክሩ።",
    "total wins": "ጠቅላላ ድሎች",
    "games": "ጨዋታዎች",
    "music": "ሙዚቃ",
    "redeem": "ይበዙ",
    "logout": "ውጣ",
    "english": "እንግሊዝኛ",
    "amharic": "አማርኛ",
    "sign up": "ይመዝገቡ",
    "etb":"ብር",
    "amount":'መጠን',
    "select avatar":" አቫታር ምረጥ",
    "edit profile":"ፕሮፋይል አስተካክል",
    "edit username":"የተጠቃሚ ስም አስተካክል",
    "gender":"ጾታ",
    "male":"ወንድ",
    "female":"ሴት",
    "update":"ቀይር",
    "profile":"ፕሮፋይል",
    "update profile photo":"ፕሮፋይል ፎቶ ቀይር",
    "upload from gallery":"ከጋለሪ ጫን",
    "capture photo":"ፎቶ አንሳ",
    "cancel":"ሰርዝ",
    "capture":"አንሳ",
    "updating":"እየቀየረ ነው ",
    "gender":"ጾታ",
    "enter new name":"አዲስ የተጠቃሚ ስም አስገባ"

};

export default data;